import time
import streamlit as st
from PIL import Image

from utils import styling, data_loader, model_utils

st.set_page_config(page_title="Analyze My Plant — RiceCare AI", page_icon="📷", layout="wide")
styling.inject_global_css()

st.markdown("## 📷 Analyze Your Rice Plant")
st.caption("Upload a clear photo of a rice leaf to get AI-based prediction scores across all four classes.")

if model_utils.is_demo_mode():
    st.info("⚙️ **Demo Mode** — no trained model file found in `/model`. Scores below are generated by a "
            "placeholder heuristic so you can test the full app. Drop `rice_disease_model.h5` or "
            "`.keras` into `/model` to activate real predictions — no code changes needed.")

upload_col, preview_col = st.columns([1, 1])

with upload_col:
    uploaded_file = st.file_uploader(
        "Drag & drop or browse a rice leaf image",
        type=["jpg", "jpeg", "png"],
        help="Best results with a clear, well-lit, close-up photo of a single leaf.",
    )
    camera_image = st.camera_input("Or take a photo")

image_source = uploaded_file or camera_image

with preview_col:
    if image_source is not None:
        image = Image.open(image_source)
        st.image(image, caption="Image Preview", use_container_width=True)
        if st.button("✖️ Remove Image"):
            st.rerun()
    else:
        st.markdown(
            """<div class="rc-card" style="text-align:center; padding:3rem 1rem;">
            <h4>📷 Upload Image</h4>
            <p>Drag &amp; drop a rice leaf photo, or use your camera above.</p>
            </div>""",
            unsafe_allow_html=True,
        )

st.markdown("<br/>", unsafe_allow_html=True)

analyze_clicked = st.button("🔍 ANALYZE", type="primary", use_container_width=True, disabled=image_source is None)

if analyze_clicked and image_source is not None:
    image = Image.open(image_source)

    progress_box = st.empty()
    stages = [
        "🔎 Analyzing image...",
        "🧩 Checking visual patterns...",
        "🤖 Running AI model...",
        "📊 Generating prediction...",
    ]
    for stage in stages:
        progress_box.info(stage)
        time.sleep(0.35)
    progress_box.empty()

    scores = model_utils.predict(image)
    top_id, top_score = model_utils.get_top_prediction(scores)

    st.session_state["rc_last_scores"] = scores
    st.session_state["rc_last_top"] = top_id
    st.session_state["rc_last_image_bytes"] = image_source.getvalue()

# ---------------- RESULTS ----------------
if "rc_last_scores" in st.session_state:
    scores = st.session_state["rc_last_scores"]
    top_id = st.session_state["rc_last_top"]
    disease_info = data_loader.get_disease_info(top_id)

    st.markdown("---")
    st.markdown("### 🤖 AI Prediction")

    st.markdown(
        f"""
        <div class="rc-result-headline">
            <div class="rc-label">Most likely condition</div>
            <div class="rc-disease-name">{disease_info['emoji']} {disease_info['disease_name']}</div>
            <div>Model prediction score: <b>{scores[top_id]*100:.1f}%</b></div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.caption("Model prediction scores (not a guaranteed diagnosis)")
    for disease_id in sorted(scores, key=scores.get, reverse=True):
        info = data_loader.get_disease_info(disease_id)
        pct = scores[disease_id] * 100
        st.markdown(f"**{info['emoji']} {info['disease_name']}** — {pct:.1f}%")
        st.progress(min(max(scores[disease_id], 0.0), 1.0))

    # ---------------- COMPARE WITH SAMPLE IMAGES ----------------
    st.markdown("---")
    st.markdown("### 👀 Compare Your Plant")
    st.caption("Compare the visible symptoms with these representative examples. "
               "Visual comparison alone does not confirm a diagnosis.")

    cmp1, cmp2 = st.columns([1, 2])
    with cmp1:
        st.markdown("**Your Image**")
        st.image(st.session_state["rc_last_image_bytes"], use_container_width=True)
    with cmp2:
        st.markdown(f"**Typical {disease_info['disease_name']}**")
        sample_paths = data_loader.get_sample_images(top_id)
        if sample_paths:
            cols = st.columns(len(sample_paths))
            for c, path in zip(cols, sample_paths):
                c.image(path, use_container_width=True)
        else:
            st.warning(
                f"No sample images found yet for **{disease_info['disease_name']}**. "
                f"Add reference photos to `data/sample_images/"
                f"{data_loader.DISEASE_ID_TO_FOLDER.get(top_id, '')}/`."
            )

    # ---------------- DISEASE INFO ----------------
    st.markdown("---")
    st.markdown(f"### {disease_info['emoji']} {disease_info['disease_name']}")

    if top_id != "HEALTHY":
        st.markdown(f"**🧫 Caused by:** {disease_info['causal_organism']} ({disease_info['causative_agent']})")

    st.write(disease_info["description"])

    dcol1, dcol2 = st.columns(2)
    with dcol1:
        st.markdown("**🔎 Common Symptoms**")
        if disease_info["symptoms"]:
            for s in disease_info["symptoms"]:
                st.markdown(f"- {s}")
        else:
            st.caption("No symptom data available.")
    with dcol2:
        header = "🌾 General Management" if top_id != "HEALTHY" else "🌾 Recommended Practices"
        st.markdown(f"**{header}**")
        if disease_info["management"]:
            for m in disease_info["management"]:
                st.markdown(f"- {m}")
        else:
            st.caption("No management data available.")

    # ---------------- MOLECULAR CTA ----------------
    st.markdown("<br/>", unsafe_allow_html=True)
    st.markdown(
        """<div class="rc-card">
        <h4>🧬 Explore Molecular Information</h4>
        <p>The AI predicts the visual disease class. The molecular information below is separately
        researched and describes rice defense/stress-related proteins associated with the biological
        response to the selected condition — it is not detected from the photograph itself.</p>
        </div>""",
        unsafe_allow_html=True,
    )
    if st.button("🧬 Explore Molecular Information for This Result", type="primary"):
        st.session_state["rc_molecular_disease_id"] = top_id
        st.switch_page("pages/3_Molecular_Information.py")

    styling.disclaimer()

styling.footer()
